# Generated by Django 5.1.4 on 2024-12-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_remove_user_role_user_name_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('manager', 'Manager')], default='farmer', max_length=10),
        ),
    ]
