# Generated by Django 5.1.4 on 2024-12-26 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.FloatField()),
                ('current_stock', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SiloLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('ADD', 'Addition'), ('REMOVE', 'Removal')], max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('silo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='silos.silo')),
            ],
        ),
    ]
