# Generated by Django 5.1.4 on 2024-12-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silos', '0002_rename_silo_id_silolog_silo_alter_silo_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silo',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='silolog',
            name='change_type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=50),
        ),
    ]
