# Generated by Django 5.1.4 on 2024-12-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silos', '0003_alter_silo_current_stock_alter_silolog_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silolog',
            name='change_type',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=50),
        ),
    ]
